exp_name: resnet18_ours_mnist
net: resnet18_ours_cbam_multi
dataset: MNIST
#image_folder: /data2/wangtan/causal-invariant-attention/dataset/NICO/multi_classification
#cxt_dic_path: /data2/wangtan/causal-invariant-attention/dataset/NICO/label_file/Context_name2label.json
#class_dic_path: /data2/wangtan/causal-invariant-attention/dataset/NICO/label_file/Animal_name2label.json
train_root: /home/prebenness/workspace/CaaM_representations/2-StandardDatasets/data/mnist_dumb_debug/train
val_root: /home/prebenness/workspace/CaaM_representations/2-StandardDatasets/data/mnist_dumb_debug/val
#imageneta_root: /disk2/wangtan/dataset/ImageNet/imagenet_a/imagenet-a
training_opt:
  seed: 0
  classes: 10
  batch_size: 10
  val_batch_size: 10
  lr: 0.1
  warm: 2
  epoch: 120
  milestones: [50, 80, 100]
  save_epoch: 20
  print_batch: 10
  num_workers: 1
variance_opt:
  #balance_factor: 0.02
  env: True
  mode: 'ours'
  erm_flag: True
  sp_flag: False
  n_env: 5
  env_type: 'random'
  #env_type: 'auto-iter'
  split_renew: 40
  split_renew_iters: 10
  from_scratch: False
  #ref_model: resnet18
  #ref_model_path: /disk2/wangtan/code/causal_invariant_attention/multi-classification/imagenet/checkpoint/resnet18/baseline_resnet18_imagenet9_lr0.05_class9/resnet18-100-regular.pth
  penalty_weight: 5e4
  penalty_anneal_iters: 0
  #2 blocks, 4 layers
  split_layer: 3
resume: False